apiVersion: v1
kind: ConfigMap
metadata:
  name: highscore-config
data:
  configuration.yaml: "aws:\r\n  region_name: eu-central-1\r\n  dynamodb:\r\n    endpoint_url: http://dynamodb-local:8000\r\n\r\nhighscore:\r\n  table_name: Scores\r\n"
