name: Docker Image CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag highscore:${{ github.run_id }}

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: docker push highscore:${{ github.run_id }}

      - name: Tag latest image
        run: docker tag highscore:latest

      - name: Push latest image
        run: docker push highscore:latest
