name: Docker Image PR
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: torben/highscore
      IMAGE_ID: $IMAGE_NAME:${{ github.run_number }}-${{ github.run_attempt }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag $IMAGE_ID

      - name: Log in to Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          username: torben
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push image
        run: docker push $IMAGE_ID
