name: Docker Image Main
on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: torben/highscore

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: |
          echo "IMAGE_ID=$IMAGE_NAME:${{ github.run_number }}-${{ github.run_attempt }}" >> $GITHUB_ENV
          echo "IMAGE_ID_LATEST=$IMAGE_NAME:latest" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ env.IMAGE_ID }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          username: torben
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push image
        run: docker push ${{ env.IMAGE_ID }}

      - name: Tag latest image
        run: docker tag ${{ env.IMAGE_ID}} ${{ env.IMAGE_ID_LATEST }}

      - name: Push latest image
        run: docker push ${{ env.IMAGE_ID_LATEST }}
