name: Docker Image CI
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag torben/highscore:${{ github.run_number }}-${{ github.run_attempt }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          username: torben
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push image
        run: docker push torben/highscore:${{ github.run_number }}-${{ github.run_attempt }}
